search_algorithm: pso_regular # Options: pso, ga, local_search, pso_regular
cost_function: revenue  # Options: sphere, schwefel, schaffer, griewank, func7, func8, func9, func11, revenue
dimension: 2
x_initial: null  # A d-dimensional list, such as [1.0, -1.0], or null. If null, the x_initial will be a random point in the domain.
neighborhood_plot_method: all # Options: single, all

local_search:
  max_itr: 500
  convergence_threshold: 0.001

ga:
  max_itr: 500  # max_itr = number of generations - specifies how many times the GA will evolve the population
  population_size: 10  # Number of individuals (candidate solutions) in each generation/iteration of the GA
  mutation_rate: 0.1  # The probability that a new offspring will undergo mutation
  crossover_rate: 0.8  # The probability that two selected individuals (parents) will undergo crossover to produce offspring

pso_regular:
  max_itr: 500
  num_particles: 10
  alpha_1: 0.01
  alpha_2: 0.01
  alpha_3: 0.01
  local_best_option: 'so_far'  # Options: this_iteration, so_far
  global_best_option: 'so_far'  # Options: this_iteration, so_far
  local_search:
    max_itr: 100
    convergence_threshold: 0.01

    
pso:
  max_itr: 500
  max_elixir: 20
  local_best_option: 'so_far'  # Options: this_iteration, so_far
  global_best_option: 'so_far'  # Options: this_iteration, so_far
  local_search:
    max_itr: 100
    convergence_threshold: 0.01
  
  troops:
      giant:
        elixir_cost: 5
        alpha_values:
          alpha_1: 0.13
          alpha_2: 0.12
          alpha_3: 0.12
      archer:
        elixir_cost: 3
        alpha_values:
          alpha_1: 1.74
          alpha_2: 4.84
          alpha_3: 1.66
      goblin:
        elixir_cost: 2
        alpha_values:
          alpha_1: 4.21
          alpha_2: 3.42
          alpha_3: 2.60
      wizard:
        elixir_cost: 4
        alpha_values:
          alpha_1: 2.82
          alpha_2: 2.82
          alpha_3: 2.81
      dragon:
        elixir_cost: 10
        alpha_values:
          alpha_1: 5.00
          alpha_2: 9.00
          alpha_3: 7.10
      hog_rider:
        elixir_cost: 6
        alpha_values:
          alpha_1: 3.04
          alpha_2: 4.32
          alpha_3: 3.71
